import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import Screen from '../components/ScreenWrapper';
import { Button, Card, Empty, IconButton, Input, Loading, Pagination, money } from '../components/UI';
import { api, message } from '../api/api';
import { useAuth } from '../context/AuthContext';
import colors from '../theme/colors';

const PAGE_SIZE = 6;

function Header({ title, subtitle, action }) {
  return <View style={s.header}><View style={{ flex: 1 }}><Text style={s.title}>{title}</Text>{subtitle ? <Text style={s.subtitle}>{subtitle}</Text> : null}</View>{action}</View>;
}

function Form({ title, children }) {
  return <Screen><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.form}><Header title={title} />{children}</ScrollView></KeyboardAvoidingView></Screen>;
}

function SearchToolbar({ value, onChange, order, onOrder }) {
  return <View style={s.toolbar}><Input icon="search-outline" style={s.search} placeholder="Buscar..." value={value} onChangeText={onChange} /><IconButton icon={order === 'az' ? 'arrow-down-outline' : 'arrow-up-outline'} active onPress={onOrder} /></View>;
}

function usePagination(items, resetKey) {
  const [page, setPage] = useState(1);
  const totalPages = Math.max(1, Math.ceil(items.length / PAGE_SIZE));
  useEffect(() => setPage(1), [resetKey]);
  useEffect(() => { if (page > totalPages) setPage(totalPages); }, [page, totalPages]);
  return { page, setPage, totalPages, visible: items.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE) };
}

export function Login({ navigation }) {
  const { login } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false);
  const send = async () => { try { setBusy(true); await login(email.trim().toLowerCase(), password); } catch (error) { Alert.alert('No se pudo ingresar', message(error)); } finally { setBusy(false); } };
  return <Form title="Ciento Once"><Text style={s.welcome}>Gestioná tu negocio de forma simple</Text><Input icon="mail-outline" placeholder="Email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} /><Input icon="lock-closed-outline" placeholder="Contraseña" secureTextEntry value={password} onChangeText={setPassword} /><Button title={busy ? 'Ingresando…' : 'Ingresar'} disabled={busy} onPress={send} /><Button secondary title="Crear una cuenta" onPress={() => navigation.navigate('Registro')} /></Form>;
}

export function Registro({ navigation }) {
  const { register } = useAuth(); const [value, setValue] = useState({ nombre: '', email: '', password: '', confirmar: '' }); const [busy, setBusy] = useState(false);
  const change = (key, text) => setValue(current => ({ ...current, [key]: text }));
  const send = async () => { if (value.password !== value.confirmar) return Alert.alert('Revisá los datos', 'Las contraseñas no coinciden'); try { setBusy(true); await register(value); } catch (error) { Alert.alert('No se pudo crear la cuenta', message(error)); } finally { setBusy(false); } };
  return <Form title="Crear cuenta"><Input icon="person-outline" placeholder="Nombre" value={value.nombre} onChangeText={text => change('nombre', text)} /><Input icon="mail-outline" placeholder="Email" autoCapitalize="none" value={value.email} onChangeText={text => change('email', text)} /><Input icon="lock-closed-outline" placeholder="Contraseña (6 a 12 caracteres)" secureTextEntry value={value.password} onChangeText={text => change('password', text)} /><Input icon="shield-checkmark-outline" placeholder="Confirmar contraseña" secureTextEntry value={value.confirmar} onChangeText={text => change('confirmar', text)} /><Button title={busy ? 'Creando…' : 'Crear cuenta'} disabled={busy} onPress={send} /><Button secondary title="Regresar" onPress={() => navigation.goBack()} /></Form>;
}

export function Home({ navigation }) {
  const { session, logout } = useAuth(); const [data, setData] = useState(null); const [menu, setMenu] = useState(false);
  useFocusEffect(useCallback(() => { let active = true; api.get('/dashboard').then(response => { if (active) setData(response.data.data); }).catch(() => {}); return () => { active = false; }; }, []));
  const go = name => { setMenu(false); navigation.navigate(name); };
  return <Screen><ScrollView contentContainerStyle={s.page}><Header title={`Hola, ${session?.usuario?.nombre || ''}`} subtitle="¿Qué vamos a organizar hoy?" action={<IconButton icon="menu" active onPress={() => setMenu(true)} />} /><View style={s.quickGrid}><Pressable style={s.quickCard} onPress={() => go('NuevoPedido')}><View style={s.quickIcon}><Ionicons name="receipt-outline" size={27} color="#FFF" /></View><Text style={s.quickTitle}>Nuevo pedido</Text><Text style={s.quickText}>Registrar una venta</Text></Pressable><Pressable style={s.quickCard} onPress={() => go('NuevaCompra')}><View style={s.quickIcon}><Ionicons name="cart-outline" size={27} color="#FFF" /></View><Text style={s.quickTitle}>Nueva compra</Text><Text style={s.quickText}>Cargar un gasto</Text></Pressable></View><Text style={s.sectionTitle}>Próximos pedidos</Text>{data ? (data.pedidos_proximos?.length ? data.pedidos_proximos.slice(0, 6).map(item => <Card key={item.id_pedido}><View style={s.spaceBetween}><Text style={s.cardTitle}>{item.cliente_nombre}</Text><Text style={s.amount}>{money(item.total)}</Text></View><Text style={s.meta}>{String(item.fecha_entrega).slice(0, 10)} · {item.pagado ? 'Pagado' : 'Pago pendiente'}</Text><StatusPill active={item.estado === 'entregado'} text={item.estado} /></Card>) : <Empty text="No hay pedidos próximos" />) : <Loading />}</ScrollView><Modal visible={menu} transparent animationType="fade" onRequestClose={() => setMenu(false)}><Pressable style={s.overlay} onPress={() => setMenu(false)}><Pressable style={s.drawer} onPress={() => {}}><Text style={s.drawerTitle}>Menú</Text>{[['people-outline','Clientes','Clientes'],['cube-outline','Productos','Productos'],['leaf-outline','Insumos','Insumos'],['calculator-outline','Calculadora de costos','Calculadora']].map(([icon, label, route]) => <Pressable key={route} style={s.menuItem} onPress={() => go(route)}><Ionicons name={icon} size={22} color={colors.primaryDark} /><Text style={s.menuText}>{label}</Text><Ionicons name="chevron-forward" size={18} color={colors.textSecondary} /></Pressable>)}<Button danger icon="log-out-outline" title="Cerrar sesión" onPress={logout} /></Pressable></Pressable></Modal></Screen>;
}

const crudConfig = {
  Productos: { path: 'productos', title: 'Productos', icon: 'cube-outline', fields: [['nombre','Nombre'],['descripcion','Descripción'],['precio_venta','Precio de venta'],['costo_estimado','Costo estimado'],['stock_actual','Stock inicial']], defaults: { categoria: 'dulce', stock_actual: '0' } },
  Clientes: { path: 'clientes', title: 'Clientes', icon: 'people-outline', fields: [['nombre','Nombre'],['telefono','Teléfono'],['direccion','Dirección'],['observacion','Observación']], defaults: {} },
  Insumos: { path: 'insumos', title: 'Insumos', icon: 'leaf-outline', fields: [['nombre','Nombre'],['descripcion','Descripción'],['precio_referencia','Precio de referencia'],['cantidad_referencia','Cantidad de referencia']], defaults: { tipo_medida: 'peso', unidad_referencia: 'g', fecha_precio: new Date().toISOString().slice(0, 10) } },
};

export function CrudList({ route, navigation }) {
  const config = crudConfig[route.name]; const [rows, setRows] = useState([]); const [search, setSearch] = useState(''); const [order, setOrder] = useState('az'); const [category, setCategory] = useState('dulce'); const [form, setForm] = useState(config.defaults); const [editing, setEditing] = useState(null); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); api.get(`/${config.path}`, { params: { limit: 100 } }).then(response => setRows(response.data.data)).catch(error => Alert.alert('Error', message(error))).finally(() => setLoading(false)); }, [config.path]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const filtered = useMemo(() => rows.filter(item => item.nombre.toLowerCase().includes(search.toLowerCase())).filter(item => route.name !== 'Productos' || item.categoria === category).sort((a, b) => order === 'az' ? a.nombre.localeCompare(b.nombre) : b.nombre.localeCompare(a.nombre)), [rows, search, order, category, route.name]);
  const pages = usePagination(filtered, `${search}-${order}-${category}`);
  const openNew = () => { setEditing(null); setForm(config.defaults); setFormOpen(true); };
  const save = async () => { try { editing ? await api.put(`/${config.path}/${editing}`, form) : await api.post(`/${config.path}`, form); setFormOpen(false); load(); } catch (error) { Alert.alert('No se pudo guardar', message(error)); } };
  const remove = id => Alert.alert('Eliminar', '¿Seguro que querés eliminar este registro?', [{ text: 'Cancelar' }, { text: 'Eliminar', style: 'destructive', onPress: async () => { await api.patch(`/${config.path}/${id}/desactivar`); load(); } }]);
  return <Screen><FlatList contentContainerStyle={s.page} data={pages.visible} keyExtractor={item => String(item[Object.keys(item).find(key => key.startsWith('id_'))])} ListHeaderComponent={<><Header title={config.title} subtitle={`${filtered.length} registros`} action={<IconButton icon="add" active onPress={openNew} />} />{route.name === 'Productos' ? <View style={s.segment}><Pressable onPress={() => setCategory('dulce')} style={[s.segmentButton, category === 'dulce' && s.segmentActive]}><Text style={[s.segmentText, category === 'dulce' && s.segmentTextActive]}>Dulces</Text></Pressable><Pressable onPress={() => setCategory('salado')} style={[s.segmentButton, category === 'salado' && s.segmentActive]}><Text style={[s.segmentText, category === 'salado' && s.segmentTextActive]}>Salados</Text></Pressable></View> : null}<SearchToolbar value={search} onChange={setSearch} order={order} onOrder={() => setOrder(current => current === 'az' ? 'za' : 'az')} />{route.name === 'Insumos' ? <Button secondary icon="calculator-outline" title="Calculadora de costos" onPress={() => navigation.navigate('Calculadora')} /> : null}</>} ListEmptyComponent={loading ? <Loading /> : <Empty />} renderItem={({ item }) => { const id = item[Object.keys(item).find(key => key.startsWith('id_'))]; return <Card><View style={s.spaceBetween}><View style={{ flex: 1 }}><Text style={s.cardTitle}>{item.nombre}</Text>{item.precio_venta !== undefined ? <><Text style={s.amount}>{money(item.precio_venta)}</Text><Text style={s.meta}>{item.categoria} · Stock {item.stock_actual}</Text></> : null}{item.telefono !== undefined ? <Text style={s.meta}>{item.telefono || 'Sin teléfono'} · {item.direccion || 'Sin dirección'}</Text> : null}{item.precio_referencia !== undefined ? <Text style={s.meta}>{money(item.precio_referencia)} por {item.cantidad_referencia} {item.unidad_referencia}</Text> : null}</View></View><View style={s.actionRow}><Button compact secondary icon="create-outline" title="Editar" style={{ flex: 1 }} onPress={() => { setEditing(id); setForm({ ...item }); setFormOpen(true); }} /><IconButton danger icon="trash-outline" onPress={() => remove(id)} /></View></Card>; }} ListFooterComponent={<Pagination {...pages} onChange={pages.setPage} />} /><CrudModal visible={formOpen} config={config} form={form} setForm={setForm} editing={editing} onClose={() => setFormOpen(false)} onSave={save} /></Screen>;
}

function CrudModal({ visible, config, form, setForm, editing, onClose, onSave }) {
  const numberField = key => ['precio_venta','costo_estimado','stock_actual','precio_referencia','cantidad_referencia'].includes(key);
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><Form title={editing ? `Editar ${config.title.toLowerCase()}` : `Nuevo ${config.title.toLowerCase()}`}>{config.fields.map(([key, label]) => <Input key={key} placeholder={label} keyboardType={numberField(key) ? 'decimal-pad' : 'default'} value={String(form[key] ?? '')} onChangeText={text => setForm(current => ({ ...current, [key]: numberField(key) ? text.replace(',', '.') : text }))} />)}{config.path === 'productos' ? <><Text style={s.label}>Categoría</Text><View style={s.segment}><Pressable onPress={() => setForm(current => ({ ...current, categoria: 'dulce' }))} style={[s.segmentButton, form.categoria === 'dulce' && s.segmentActive]}><Text style={[s.segmentText, form.categoria === 'dulce' && s.segmentTextActive]}>Dulce</Text></Pressable><Pressable onPress={() => setForm(current => ({ ...current, categoria: 'salado' }))} style={[s.segmentButton, form.categoria === 'salado' && s.segmentActive]}><Text style={[s.segmentText, form.categoria === 'salado' && s.segmentTextActive]}>Salado</Text></Pressable></View></> : null}{config.path === 'insumos' ? <><Text style={s.label}>Tipo y unidad</Text><View style={s.chips}>{[['peso','g'],['volumen','ml'],['unidad','unidad']].map(([type, unit]) => <Pressable key={type} onPress={() => setForm(current => ({ ...current, tipo_medida: type, unidad_referencia: unit }))} style={[s.chip, form.tipo_medida === type && s.chipActive]}><Text style={form.tipo_medida === type ? s.chipTextActive : s.chipText}>{type}</Text></Pressable>)}</View></> : null}<Button icon="checkmark" title="Guardar" onPress={onSave} /><Button secondary title="Cancelar" onPress={onClose} /></Form></Modal>;
}

function StatusPill({ active, text }) { return <View style={[s.pill, active && s.pillActive]}><Text style={[s.pillText, active && s.pillTextActive]}>{text}</Text></View>; }

export function Pedidos({ navigation }) {
  const [rows, setRows] = useState([]); const [order, setOrder] = useState('fechaAsc'); const [filter, setFilter] = useState('todos');
  const load = useCallback(() => api.get('/pedidos').then(response => setRows(response.data.data)).catch(error => Alert.alert('Error', message(error))), []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const filtered = useMemo(() => rows.filter(item => filter === 'todos' || item.estado === filter).sort((a, b) => order === 'fechaAsc' ? String(a.fecha_entrega).localeCompare(String(b.fecha_entrega)) : String(b.fecha_entrega).localeCompare(String(a.fecha_entrega))), [rows, order, filter]);
  const pages = usePagination(filtered, `${order}-${filter}`);
  const toggleDelivered = async item => { await api.patch(`/pedidos/${item.id_pedido}/estado`, { estado: item.estado === 'entregado' ? 'pendiente' : 'entregado' }); load(); };
  return <Screen><FlatList contentContainerStyle={s.page} data={pages.visible} keyExtractor={item => String(item.id_pedido)} ListHeaderComponent={<><Header title="Pedidos" subtitle={`${filtered.length} pedidos`} action={<IconButton icon="add" active onPress={() => navigation.navigate('NuevoPedido')} />} /><View style={s.filterRow}>{['todos','pendiente','entregado'].map(value => <Pressable key={value} onPress={() => setFilter(value)} style={[s.chip, filter === value && s.chipActive]}><Text style={filter === value ? s.chipTextActive : s.chipText}>{value}</Text></Pressable>)}<IconButton icon={order === 'fechaAsc' ? 'arrow-down-outline' : 'arrow-up-outline'} active onPress={() => setOrder(current => current === 'fechaAsc' ? 'fechaDesc' : 'fechaAsc')} /></View></>} ListEmptyComponent={<Empty text="No hay pedidos" />} renderItem={({ item }) => <Card><View style={s.spaceBetween}><Text style={s.cardTitle}>{item.cliente_nombre}</Text><Text style={s.amount}>{money(item.total)}</Text></View><Text style={s.meta}>{item.detalle_resumido}</Text><Text style={s.meta}>Entrega: {String(item.fecha_entrega).slice(0, 10)}</Text><View style={s.spaceBetween}><Pressable onPress={() => toggleDelivered(item)} style={[s.deliveryButton, item.estado === 'entregado' && s.deliveryActive]}><Ionicons name="checkmark-circle-outline" size={19} color={item.estado === 'entregado' ? '#FFF' : colors.textSecondary} /><Text style={[s.deliveryText, item.estado === 'entregado' && { color: '#FFF' }]}>{item.estado === 'entregado' ? 'Entregado' : 'Marcar entregado'}</Text></Pressable><View style={s.switchWrap}><Text style={s.meta}>Pagado</Text><Switch trackColor={{ true: colors.primary }} value={!!item.pagado} onValueChange={async value => { await api.patch(`/pedidos/${item.id_pedido}/pagado`, { pagado: value }); load(); }} /></View></View><View style={s.actionRow}><Button compact secondary icon="create-outline" title="Editar" style={{ flex: 1 }} onPress={() => navigation.navigate('NuevoPedido', { idPedido: item.id_pedido })} /><IconButton danger icon="trash-outline" onPress={() => Alert.alert('Eliminar pedido', '¿Eliminar y restaurar su stock?', [{ text: 'Cancelar' }, { text: 'Eliminar', style: 'destructive', onPress: async () => { await api.patch(`/pedidos/${item.id_pedido}/desactivar`); load(); } }])} /></View></Card>} ListFooterComponent={<Pagination {...pages} onChange={pages.setPage} />} /></Screen>;
}

export function Stock() {
  const [rows, setRows] = useState([]); const [search, setSearch] = useState(''); const [order, setOrder] = useState('az'); const [selected, setSelected] = useState(null); const [quantity, setQuantity] = useState(''); const [reason, setReason] = useState('');
  const load = useCallback(() => api.get('/productos', { params: { limit: 100 } }).then(response => setRows(response.data.data)).catch(error => Alert.alert('Error', message(error))), []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const filtered = useMemo(() => rows.filter(item => item.nombre.toLowerCase().includes(search.toLowerCase())).sort((a, b) => order === 'az' ? a.nombre.localeCompare(b.nombre) : b.nombre.localeCompare(a.nombre)), [rows, search, order]);
  const pages = usePagination(filtered, `${search}-${order}`);
  const move = async type => { const value = Number(quantity.replace(',', '.')); if (!Number.isInteger(value) || value < 1) return Alert.alert('Cantidad inválida', 'Ingresá un número entero mayor a cero.'); try { await api.post(`/stock/productos/${selected.id_producto}`, { tipo: type, cantidad: value, motivo: reason || 'Ajuste manual' }); setSelected(null); setQuantity(''); setReason(''); load(); } catch (error) { Alert.alert('No se pudo modificar', message(error)); } };
  return <Screen><FlatList contentContainerStyle={s.page} data={pages.visible} keyExtractor={item => String(item.id_producto)} ListHeaderComponent={<><Header title="Stock" subtitle="Control de productos disponibles" /><SearchToolbar value={search} onChange={setSearch} order={order} onOrder={() => setOrder(current => current === 'az' ? 'za' : 'az')} /></>} ListEmptyComponent={<Empty text="No hay productos" />} renderItem={({ item }) => <Card><View style={s.spaceBetween}><View><Text style={s.cardTitle}>{item.nombre}</Text><Text style={s.meta}>{item.categoria}</Text></View><View style={s.stockBadge}><Text style={s.stockNumber}>{item.stock_actual}</Text><Text style={s.stockLabel}>unidades</Text></View></View><Button compact secondary icon="options-outline" title="Editar stock" onPress={() => setSelected(item)} /></Card>} ListFooterComponent={<Pagination {...pages} onChange={pages.setPage} />} /><Modal visible={!!selected} transparent animationType="fade" onRequestClose={() => setSelected(null)}><View style={s.modalCenter}><View style={s.dialog}><Header title={selected?.nombre || ''} subtitle={`Stock actual: ${selected?.stock_actual || 0}`} action={<IconButton icon="close" onPress={() => setSelected(null)} />} /><Input icon="layers-outline" placeholder="Cantidad" keyboardType="number-pad" value={quantity} onChangeText={setQuantity} /><Input icon="chatbubble-outline" placeholder="Motivo (opcional)" value={reason} onChangeText={setReason} /><View style={s.actionRow}><Button secondary icon="remove" title="Quitar" style={{ flex: 1 }} onPress={() => move('quitar')} /><Button icon="add" title="Agregar" style={{ flex: 1 }} onPress={() => move('agregar')} /></View></View></View></Modal></Screen>;
}

export function Caja({ navigation }) {
  const [summary, setSummary] = useState(null); const [rows, setRows] = useState([]); const [type, setType] = useState(''); const [search, setSearch] = useState(''); const [order, setOrder] = useState('desc');
  const load = useCallback(() => { Promise.all([api.get('/caja/resumen'), api.get('/caja')]).then(([a, b]) => { setSummary(a.data.data); setRows(b.data.data); }).catch(error => Alert.alert('Error', message(error))); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const filtered = useMemo(() => rows.filter(item => !type || item.tipo === type).filter(item => item.concepto.toLowerCase().includes(search.toLowerCase())).sort((a, b) => order === 'desc' ? String(b.fecha_movimiento).localeCompare(String(a.fecha_movimiento)) : String(a.fecha_movimiento).localeCompare(String(b.fecha_movimiento))), [rows, type, search, order]);
  const pages = usePagination(filtered, `${type}-${search}-${order}`);
  return <Screen><FlatList contentContainerStyle={s.page} data={pages.visible} keyExtractor={item => String(item.id_movimiento_caja)} ListHeaderComponent={<><Header title="Caja" subtitle="Resumen de tu negocio" action={<IconButton icon="cart-outline" active onPress={() => navigation.navigate('NuevaCompra')} />} /><View style={s.balanceCard}><Text style={s.balanceLabel}>Balance actual</Text><Text style={s.balanceValue}>{money(summary?.balance)}</Text><View style={s.balanceDetails}><View><Text style={s.balanceSmall}>Ingresos</Text><Text style={s.income}>{money(summary?.ingresos)}</Text></View><View><Text style={s.balanceSmall}>Egresos</Text><Text style={s.expense}>{money(summary?.egresos)}</Text></View></View></View><View style={s.filterRow}>{[['','Todos'],['ingreso','Ingresos'],['egreso','Egresos']].map(([value, label]) => <Pressable key={label} onPress={() => setType(value)} style={[s.chip, type === value && s.chipActive]}><Text style={type === value ? s.chipTextActive : s.chipText}>{label}</Text></Pressable>)}</View><SearchToolbar value={search} onChange={setSearch} order={order} onOrder={() => setOrder(current => current === 'desc' ? 'asc' : 'desc')} /><Text style={s.sectionTitle}>Movimientos</Text></>} ListEmptyComponent={<Empty text="Todavía no hay movimientos" />} renderItem={({ item }) => <Card><View style={s.spaceBetween}><View style={{ flex: 1 }}><Text style={s.cardTitle}>{item.concepto}</Text><Text style={s.meta}>{String(item.fecha_movimiento).replace('T', ' ').slice(0, 16)} · {item.origen}</Text></View><Text style={[s.movementAmount, item.tipo === 'ingreso' ? s.income : s.expense]}>{item.tipo === 'ingreso' ? '+' : '−'} {money(item.monto)}</Text></View>{item.anulado ? <StatusPill text="Anulado" /> : null}</Card>} ListFooterComponent={<Pagination {...pages} onChange={pages.setPage} />} /></Screen>;
}

export function NuevoPedido({ navigation, route }) {
  const orderId = route?.params?.idPedido; const [clients, setClients] = useState([]); const [products, setProducts] = useState([]); const [clientSearch, setClientSearch] = useState(''); const [productSearch, setProductSearch] = useState(''); const [client, setClient] = useState(null); const [quantities, setQuantities] = useState({}); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [paid, setPaid] = useState(false); const [state, setState] = useState('pendiente'); const [busy, setBusy] = useState(false);
  useEffect(() => { const requests = [api.get('/clientes', { params: { limit: 100 } }), api.get('/productos', { params: { limit: 100 } })]; if (orderId) requests.push(api.get(`/pedidos/${orderId}`)); Promise.all(requests).then(([a, b, order]) => { setClients(a.data.data); setProducts(b.data.data); if (order) { const value = order.data.data; setClient(value.id_cliente); setDate(String(value.fecha_entrega).slice(0, 10)); setPaid(!!value.pagado); setState(value.estado); setQuantities(Object.fromEntries(value.detalles.map(item => [item.id_producto, item.cantidad]))); } }); }, [orderId]);
  const shownClients = clients.filter(item => item.nombre.toLowerCase().includes(clientSearch.toLowerCase())).slice(0, 5); const shownProducts = products.filter(item => item.nombre.toLowerCase().includes(productSearch.toLowerCase())).slice(0, 5);
  const total = products.reduce((sum, item) => sum + Number(item.precio_venta) * Number(quantities[item.id_producto] || 0), 0);
  const save = async () => { const body = { id_cliente: client, fecha_entrega: date, estado: state, pagado: paid, detalles: Object.entries(quantities).filter(([, value]) => value > 0).map(([id, value]) => ({ id_producto: Number(id), cantidad: value })) }; try { setBusy(true); orderId ? await api.put(`/pedidos/${orderId}`, body) : await api.post('/pedidos', body); navigation.goBack(); } catch (error) { Alert.alert('No se pudo guardar', message(error)); } finally { setBusy(false); } };
  return <Form title={orderId ? 'Editar pedido' : 'Nuevo pedido'}><Text style={s.label}>1. Elegí un cliente</Text><Input icon="search-outline" placeholder="Buscar cliente" value={clientSearch} onChangeText={setClientSearch} />{shownClients.map(item => <Pressable key={item.id_cliente} onPress={() => setClient(item.id_cliente)} style={[s.selectRow, client === item.id_cliente && s.selectRowActive]}><Text style={s.selectText}>{item.nombre}</Text>{client === item.id_cliente ? <Ionicons name="checkmark-circle" size={22} color={colors.primary} /> : null}</Pressable>)}<Text style={s.label}>2. Agregá productos</Text><Input icon="search-outline" placeholder="Buscar producto" value={productSearch} onChangeText={setProductSearch} />{shownProducts.map(item => <View key={item.id_producto} style={s.productRow}><View style={{ flex: 1 }}><Text style={s.cardTitle}>{item.nombre}</Text><Text style={s.meta}>{money(item.precio_venta)} · Stock {item.stock_actual}</Text></View><View style={s.counter}><IconButton icon="remove" onPress={() => setQuantities(current => ({ ...current, [item.id_producto]: Math.max(0, (current[item.id_producto] || 0) - 1) }))} /><Text style={s.counterText}>{quantities[item.id_producto] || 0}</Text><IconButton icon="add" active onPress={() => setQuantities(current => ({ ...current, [item.id_producto]: (current[item.id_producto] || 0) + 1 }))} /></View></View>)}<Text style={s.label}>3. Entrega y pago</Text><Input icon="calendar-outline" placeholder="AAAA-MM-DD" value={date} onChangeText={setDate} />{orderId ? <View style={s.segment}><Pressable onPress={() => setState('pendiente')} style={[s.segmentButton, state === 'pendiente' && s.segmentActive]}><Text style={[s.segmentText, state === 'pendiente' && s.segmentTextActive]}>Pendiente</Text></Pressable><Pressable onPress={() => setState('entregado')} style={[s.segmentButton, state === 'entregado' && s.segmentActive]}><Text style={[s.segmentText, state === 'entregado' && s.segmentTextActive]}>Entregado</Text></Pressable></View> : null}<View style={s.optionRow}><View><Text style={s.cardTitle}>Pedido pagado</Text><Text style={s.meta}>Genera un ingreso en caja</Text></View><Switch trackColor={{ true: colors.primary }} value={paid} onValueChange={setPaid} /></View><View style={s.totalBar}><Text style={s.totalLabel}>Total estimado</Text><Text style={s.totalValue}>{money(total)}</Text></View><Button icon="checkmark" title={busy ? 'Guardando…' : 'Guardar pedido'} disabled={busy} onPress={save} /></Form>;
}

export function NuevaCompra({ navigation }) {
  const [supplies, setSupplies] = useState([]); const [provider, setProvider] = useState(''); const [search, setSearch] = useState(''); const [quantities, setQuantities] = useState({}); const [prices, setPrices] = useState({}); const [busy, setBusy] = useState(false);
  useEffect(() => { api.get('/insumos', { params: { limit: 100 } }).then(response => setSupplies(response.data.data)); }, []);
  const visible = supplies.filter(item => item.nombre.toLowerCase().includes(search.toLowerCase())).slice(0, 6); const total = supplies.reduce((sum, item) => sum + Number(quantities[item.id_insumo] || 0) * Number(prices[item.id_insumo] ?? item.precio_referencia), 0);
  const save = async () => { try { setBusy(true); await api.post('/compras', { proveedor: provider, fecha_compra: new Date().toISOString().slice(0, 10), detalles: supplies.filter(item => Number(quantities[item.id_insumo]) > 0).map(item => ({ id_insumo: item.id_insumo, cantidad: Number(quantities[item.id_insumo]), precio_unitario: Number(prices[item.id_insumo] ?? item.precio_referencia) })) }); navigation.goBack(); } catch (error) { Alert.alert('No se pudo registrar', message(error)); } finally { setBusy(false); } };
  return <Form title="Nueva compra"><Input icon="storefront-outline" placeholder="Local o proveedor" value={provider} onChangeText={setProvider} /><Input icon="search-outline" placeholder="Buscar insumo" value={search} onChangeText={setSearch} />{visible.map(item => <Card key={item.id_insumo}><Text style={s.cardTitle}>{item.nombre}</Text><View style={s.twoColumns}><Input style={{ flex: 1 }} placeholder="Cantidad" keyboardType="decimal-pad" value={quantities[item.id_insumo] || ''} onChangeText={value => setQuantities(current => ({ ...current, [item.id_insumo]: value.replace(',', '.') }))} /><Input style={{ flex: 1 }} placeholder="Precio" keyboardType="decimal-pad" value={String(prices[item.id_insumo] ?? item.precio_referencia)} onChangeText={value => setPrices(current => ({ ...current, [item.id_insumo]: value.replace(',', '.') }))} /></View></Card>)}<View style={s.totalBar}><Text style={s.totalLabel}>Total de compra</Text><Text style={s.totalValue}>{money(total)}</Text></View><Button icon="checkmark" title={busy ? 'Registrando…' : 'Registrar compra'} disabled={busy} onPress={save} /></Form>;
}

export function Calculadora() {
  const [rows, setRows] = useState([]); const [used, setUsed] = useState({}); const [search, setSearch] = useState('');
  useEffect(() => { api.get('/insumos', { params: { limit: 100 } }).then(response => setRows(response.data.data)); }, []);
  const baseFactor = unit => unit === 'kg' || unit === 'l' ? 1000 : 1; const filtered = rows.filter(item => item.nombre.toLowerCase().includes(search.toLowerCase())); const cost = item => Number(item.precio_referencia) * Number(used[item.id_insumo] || 0) / (Number(item.cantidad_referencia) * baseFactor(item.unidad_referencia)); const total = rows.reduce((sum, item) => sum + cost(item), 0);
  return <Form title="Calculadora de costos"><Input icon="search-outline" placeholder="Buscar insumo" value={search} onChangeText={setSearch} />{filtered.slice(0, 7).map(item => <Card key={item.id_insumo}><View style={s.spaceBetween}><View><Text style={s.cardTitle}>{item.nombre}</Text><Text style={s.meta}>{money(item.precio_referencia)} / {item.cantidad_referencia} {item.unidad_referencia}</Text></View><Text style={s.amount}>{money(cost(item))}</Text></View><Input placeholder={`Cantidad usada (${item.tipo_medida === 'peso' ? 'g' : item.tipo_medida === 'volumen' ? 'ml' : 'unidad'})`} keyboardType="decimal-pad" value={used[item.id_insumo] || ''} onChangeText={value => setUsed(current => ({ ...current, [item.id_insumo]: value.replace(',', '.') }))} /></Card>)}<View style={s.totalBar}><Text style={s.totalLabel}>Costo total</Text><Text style={s.totalValue}>{money(total)}</Text></View></Form>;
}

export const s = StyleSheet.create({
  page: { padding: 18, paddingBottom: 42 }, form: { padding: 20, paddingBottom: 70 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 },
  title: { fontSize: 27, lineHeight: 33, fontWeight: '800', color: colors.text }, subtitle: { color: colors.textSecondary, marginTop: 3, fontSize: 14 }, welcome: { color: colors.textSecondary, fontSize: 17, marginTop: -12, marginBottom: 26 },
  sectionTitle: { fontSize: 20, fontWeight: '800', marginTop: 20, marginBottom: 12, color: colors.text }, cardTitle: { fontSize: 17, fontWeight: '700', color: colors.text }, meta: { color: colors.textSecondary, lineHeight: 21, marginTop: 3 }, amount: { color: colors.primaryDark, fontWeight: '800', fontSize: 16 },
  toolbar: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 7 }, search: { flex: 1, marginBottom: 0 }, spaceBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 }, actionRow: { flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 12 },
  quickGrid: { flexDirection: 'row', gap: 12 }, quickCard: { flex: 1, backgroundColor: '#FFF', borderRadius: 19, padding: 16, borderWidth: 1, borderColor: colors.border, elevation: 2 }, quickIcon: { width: 48, height: 48, borderRadius: 15, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginBottom: 13 }, quickTitle: { fontWeight: '800', fontSize: 16 }, quickText: { color: colors.textSecondary, fontSize: 12, marginTop: 3 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,.28)', alignItems: 'flex-end' }, drawer: { width: '82%', height: '100%', backgroundColor: colors.background, padding: 24, paddingTop: 70 }, drawerTitle: { fontSize: 26, fontWeight: '800', marginBottom: 24 }, menuItem: { flexDirection: 'row', alignItems: 'center', gap: 13, paddingVertical: 17, borderBottomWidth: 1, borderBottomColor: colors.border }, menuText: { flex: 1, fontSize: 16, fontWeight: '650' },
  segment: { flexDirection: 'row', backgroundColor: colors.primarySoft, borderRadius: 14, padding: 4, marginBottom: 12 }, segmentButton: { flex: 1, alignItems: 'center', padding: 11, borderRadius: 11 }, segmentActive: { backgroundColor: colors.primary }, segmentText: { color: colors.primaryDark, fontWeight: '700' }, segmentTextActive: { color: '#FFF' },
  label: { fontWeight: '800', fontSize: 16, color: colors.text, marginTop: 13, marginBottom: 10 }, chips: { flexDirection: 'row', gap: 8, marginBottom: 14, flexWrap: 'wrap' }, filterRow: { flexDirection: 'row', gap: 7, marginBottom: 13, flexWrap: 'wrap' }, chip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, backgroundColor: colors.primarySoft }, chipActive: { backgroundColor: colors.primary }, chipText: { color: colors.primaryDark, fontWeight: '700', textTransform: 'capitalize' }, chipTextActive: { color: '#FFF', fontWeight: '700', textTransform: 'capitalize' },
  pill: { alignSelf: 'flex-start', backgroundColor: '#EFEFEF', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 5, marginTop: 9 }, pillActive: { backgroundColor: colors.primarySoft }, pillText: { color: colors.textSecondary, fontWeight: '700', textTransform: 'capitalize' }, pillTextActive: { color: colors.primaryDark },
  deliveryButton: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#EEEEEE', paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, marginTop: 12 }, deliveryActive: { backgroundColor: colors.primary }, deliveryText: { color: colors.textSecondary, fontWeight: '700' }, switchWrap: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 9 },
  stockBadge: { backgroundColor: colors.primarySoft, borderRadius: 14, paddingHorizontal: 15, paddingVertical: 8, alignItems: 'center' }, stockNumber: { fontSize: 22, fontWeight: '800', color: colors.primaryDark }, stockLabel: { fontSize: 10, color: colors.textSecondary }, modalCenter: { flex: 1, backgroundColor: 'rgba(0,0,0,.3)', justifyContent: 'center', padding: 20 }, dialog: { backgroundColor: colors.background, borderRadius: 22, padding: 20 },
  balanceCard: { backgroundColor: '#111', borderRadius: 22, padding: 22, marginBottom: 16 }, balanceLabel: { color: '#BBB', fontSize: 14 }, balanceValue: { color: '#FFF', fontSize: 32, fontWeight: '800', marginVertical: 7 }, balanceDetails: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#333', paddingTop: 15, marginTop: 8 }, balanceSmall: { color: '#AAA', fontSize: 12 }, income: { color: colors.primary, fontWeight: '800' }, expense: { color: '#E46B62', fontWeight: '800' }, movementAmount: { fontSize: 15, fontWeight: '800' },
  selectRow: { backgroundColor: '#FFF', borderWidth: 1, borderColor: colors.border, borderRadius: 13, padding: 14, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 7 }, selectRowActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, selectText: { fontWeight: '650' }, productRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: colors.border }, counter: { flexDirection: 'row', alignItems: 'center', gap: 10 }, counterText: { width: 24, textAlign: 'center', fontWeight: '800', fontSize: 17 },
  optionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFF', padding: 15, borderRadius: 14, borderWidth: 1, borderColor: colors.border, marginBottom: 14 }, totalBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.primarySoft, padding: 17, borderRadius: 15, marginVertical: 14 }, totalLabel: { fontWeight: '700', color: colors.primaryDark }, totalValue: { fontSize: 21, fontWeight: '800', color: colors.primaryDark }, twoColumns: { flexDirection: 'row', gap: 8, marginTop: 11 },
});
